[tp-25]-protected route
pdybowski/healthy-food pull request #39
Opened 2022-01-22 00:12 UTC by altNameForStudying

* Uses Outlet as Route Wrapper
* Temporary logic for handling userState implemented (basic method with `logged in` property set to `false`)
* Refactored routes; now only contain paths
* Views.js for Routes definitions
* Updated ProfileTabs so it uses Views.js

https://user-images.githubusercontent.com/86930816/150615674-96a47b78-2c88-4c21-8a17-6dda946c2b82.mp4

https://user-images.githubusercontent.com/86930816/150615676-f9eaebda-a46e-4dd8-8ce7-84dbc53207bf.mp4

2022-01-22 10:00 UTC, pdybowski requested changes
please fix

2022-01-22 10:00 UTC, pdybowski commented on src/Views.js
> +                <Route
cant you load routes dynamically like it was before?

2022-01-22 10:00 UTC, pdybowski commented on src/components/userProfile/profileTabs/ProfileTabs.jsx
> +    // return routes.find((route) => route.key === key).path;
you can removethese two lines

2022-01-22 10:00 UTC, pdybowski commented on src/routes.js
> -export const routes = [
can you leave it here and just map these roues inside view file?

2022-01-22 10:00 UTC, pdybowski commented on src/routes.js
> +export const PROFILE_TABS = {
why is here? is it realetd to routes or to tabs?

2022-01-22 10:17 UTC, altNameForStudying commented on src/routes.js
> +export const PROFILE_TABS = {
To both routes and tabs as you can navigate using these urls directly to user view. 
Due to that i figured it's better to keep all accessible routes in the same place

2022-01-24 08:13 UTC, pdybowski approved these changes

2022-01-24 08:13 UTC, merged